### ISSUE TITLE
 Add flow/typescript toolchain/workflow 

### ISSUE THREAD

**Issue by markozxuu** [MAPESO/HASE#9]
First step is to add it to our dev workflow: add dependencies, linter compatibility, automatically run before push.

**Comment by markozxuu** [comment]
Both options seem good to me. The appeal of Flow to me has been that incremental adoption strategy.

**Comment by markozxuu** [comment]
I will have to evaluate both options 😸

**Comment by lfades** [comment]
Typescript wins
